_wandb:
    value:
        cli_version: 0.21.1
        e:
            f85bbt3oq6nsly1lw5wk1u10kry6jzvu:
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "510924943360"
                        used: "319057186816"
                email: aditya.solanki205@gmail.com
                executable: C:\Python\Anaconda\envs\llms\python.exe
                git:
                    commit: 4bd8062605bfd0d1a2cd5c75b9b0ad5093e99b0d
                    remote: https://github.com/adityasolanki205/LLM_Engineering_Learning.git
                host: LAPTOP-6VKNBP5S
                memory:
                    total: "16831942656"
                os: Windows-10-10.0.26200-SP0
                program: <python with no main file>
                python: CPython 3.11.13
                root: C:\Users\hp\Python\Gitrepo\LLM_Engineering_Learning
                startedAt: "2025-10-29T17:02:09.541961Z"
                writerId: f85bbt3oq6nsly1lw5wk1u10kry6jzvu
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 95
                - 97
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 95
                - 97
                - 105
            "3":
                - 2
                - 13
                - 14
                - 58
                - 61
                - 62
            "4": 3.11.13
            "5": 0.21.1
            "6": 4.55.3
            "8":
                - 1
                - 3
            "12": 0.21.1
            "13": windows-amd64
created_at:
    value: "2025-10-29 22:30:08"
error:
    value:
        code: null
        message: null
        param: null
estimated_finish:
    value: null
eval_id:
    value: null
fine_tuned_model:
    value: ft:gpt-4o-mini-2024-07-18:personal:pricer:CW3yj3CJ
finished_at:
    value: "2025-10-29 22:40:23"
hyperparameters:
    value:
        batch_size: 1
        learning_rate_multiplier: 1.8
        n_epochs: 1
id:
    value: ftjob-UG6lhINPUS1vHBpMtSFoOmIs
integrations:
    value:
        - FineTuningJobWandbIntegrationObject(type='wandb', wandb=FineTuningJobWandbIntegration(project='gpt-pricer', entity=None, name=None, tags=None, run_id='ftjob-UG6lhINPUS1vHBpMtSFoOmIs'))
metadata:
    value: null
method:
    value: Method(type='supervised', dpo=None, reinforcement=None, supervised=SupervisedMethod(hyperparameters=SupervisedHyperparameters(batch_size=1, learning_rate_multiplier=1.8, n_epochs=1)))
model:
    value: gpt-4o-mini-2024-07-18
n_train:
    value: 200
n_valid:
    value: 50
object:
    value: fine_tuning.job
organization_id:
    value: org-pTIl3RoKleqyX7UySR2wdKmZ
result_files:
    value: file-8kZ1waDPgBzWAtnwt4qtNX
seed:
    value: 42
shared_with_openai:
    value: false
status:
    value: succeeded
trained_tokens:
    value: 39031
training_file:
    value: file-TgLH9qBmePv74QwwLAEaro
usage_metrics:
    value: null
user_provided_suffix:
    value: pricer
validation_file:
    value: file-TdnojezuWypb6TC9VNoCyh
